const sdk = require('api')('@rephrase-studio-api/v1.0#aiax22wldy2399p');

sdk.postCampaignCampaign_idExport({
  campaign_id: 'rzQItamkNEAMPJLQsPJDgohYPfIxBb',
  authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhNcHdjdFl4YWlRdWg4Y0M0ejN0UCJ9.eyJpc3MiOiJodHRwczovL2F1dGgucmVwaHJhc2UuYWkvIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTc0MTEwOTI5NTU3ODAyMjgzNTUiLCJhdWQiOlsiaHR0cHM6Ly9kaXkucmVwaHJhc2UuYWkvYXV0aDAiLCJodHRwczovL3JlcGhyYXNlYWktcHJvZC51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjc5NzQ2MDI0LCJleHAiOjE2Nzk4MzI0MjQsImF6cCI6IjNLVTVqdkVxV0pCQ1VLblBYMjZvbmFTUHkzakozMEo0Iiwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSByZWFkOnJlcGhyYXNlLmFpIGFsbDpkaXkgcmVhZDpyZXBocmFzZS5haSJ9.aLRrWVlAdNHhcgiMPUNetbaxn-SzbWeij8ron1xfqNSs7ZwuxN5ZiCwgBibk--cQyhg92FVDbNnVpVAfmCHJWOKsxPRsu-jndcz0M2mVorvhUh2SXOyYQ9HGPJDneDqdy60aCbIYlI647HQtkJ6Y13tcMfQwSIPUcm7uR5WubyGeQ9zVDXk2SLyhS8JGPdbGaIxpgkIu39pm_t6a3LXnakWKdlLCLygUvCrHCl9d23nTvEWj1GunjdgPT-ABz4xzdyS488_B7Ei2g_4EmxnlrcCkInr6AsVTlRc5DaEZXGT7osTGMwImbF761TDgcDZszrh-B1uqcdFTxIP2Pi9b5A'
})
  .then(({ data }) => console.log(data))
  .catch(err => console.error(err));